"use client";
/* eslint-disable @next/next/no-img-element */

import React, { useEffect, useRef, useState } from "react";
import { ArrowLeft, ImagePlus, Info, Loader2, Send, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { UserAvatarCompact } from "@/components/ui/UserAvatar";
import type { ApiAttachment, ApiConversation, ApiMessage } from "@/types/api/messages";

function formatDivider(ts: number) { const d = new Date(ts); const today = new Date().toDateString(); if (d.toDateString() === today) return "Today"; return d.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" }); }
function formatTime(ts: number) { return new Date(ts).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }); }
function showDivider(messages: ApiMessage[], idx: number) { return idx === 0 || new Date(messages[idx].createdAt).toDateString() !== new Date(messages[idx - 1].createdAt).toDateString(); }

interface Props { conversation: ApiConversation; messages: ApiMessage[]; loading: boolean; loadingOlder?: boolean; hasMore?: boolean; refreshing?: boolean; error?: string | null; onBack: () => void; onLoadOlder: () => void; onSend: (text: string, attachments?: ApiAttachment[]) => Promise<void>; onToggleDetails: () => void; detailsVisible: boolean; t: (k: string, d: string) => string; currentUserId: string; }

const templates = ["Hi! I’m checking on this stay.", "Thanks — that works for me.", "Could you share a little more detail?", "I’ll get back to you shortly."];

export default function ChatArea({ conversation, messages, loading, loadingOlder, hasMore, refreshing, error, onBack, onLoadOlder, onSend, onToggleDetails, detailsVisible, t, currentUserId }: Props) {
  const [text, setText] = useState("");
  const [attachments, setAttachments] = useState<ApiAttachment[]>([]);
  const [sending, setSending] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const name = conversation.otherPerson?.name || (conversation.type === "host_guest" ? "StayNeos host" : "Guest");

  useEffect(() => { const el = scrollRef.current; if (!el || loadingOlder) return; el.scrollTo({ top: el.scrollHeight, behavior: "smooth" }); }, [messages.length, loadingOlder]);
  useEffect(() => { const ta = textareaRef.current; if (!ta) return; ta.style.height = "auto"; ta.style.height = `${Math.min(ta.scrollHeight, 128)}px`; }, [text]);

  async function handleSend() { if ((!text.trim() && attachments.length === 0) || sending) return; setSending(true); try { await onSend(text.trim(), attachments); setText(""); setAttachments([]); } finally { setSending(false); textareaRef.current?.focus(); } }
  function onKeyDown(e: React.KeyboardEvent) { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleSend(); } }
  function onFiles(files: FileList | null) { const file = files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setAttachments([{ type: "image", url: String(reader.result), name: file.name, size: file.size }]); reader.readAsDataURL(file); }

  return <div className="flex h-full min-w-0 flex-col bg-white">
    <div className="shrink-0 border-b border-neutral-200 bg-white px-4 py-3 md:px-6"><div className="flex items-center gap-3"><button type="button" onClick={onBack} className="flex h-10 w-10 items-center justify-center rounded-full hover:bg-neutral-100 md:hidden" aria-label="Back"><ArrowLeft className="h-5 w-5" /></button><UserAvatarCompact name={name} image={conversation.otherPerson?.avatar || null} className="!h-11 !w-11" /><div className="min-w-0 flex-1"><p className="truncate text-base font-semibold text-neutral-950">{name}</p><p className="truncate text-xs text-neutral-500">{conversation.property?.title || "StayNeos conversation"}{refreshing ? <span className="ml-2 text-[#00A699]">refreshing…</span> : null}</p></div><button type="button" onClick={onToggleDetails} className={cn("flex h-10 items-center gap-2 rounded-full border px-4 text-sm font-semibold", detailsVisible ? "border-neutral-950 bg-neutral-950 text-white" : "border-neutral-200 text-neutral-800 hover:bg-neutral-50")}><Info className="h-4 w-4" /><span className="hidden sm:inline">Details</span></button></div></div>
    <div ref={scrollRef} className="flex-1 overflow-y-auto bg-[#F7F7F7] px-4 py-5 md:px-8"><div className="mx-auto max-w-3xl">{hasMore ? <div className="mb-4 flex justify-center"><button onClick={onLoadOlder} disabled={loadingOlder} className="rounded-full border border-neutral-200 bg-white px-4 py-2 text-xs font-bold text-neutral-700 shadow-sm hover:shadow">{loadingOlder ? "Loading…" : "Load earlier messages"}</button></div> : null}{loading ? <div className="flex justify-center py-20"><Loader2 className="h-7 w-7 animate-spin text-neutral-400" /></div> : null}{error && !loading ? <div className="rounded-3xl border border-red-100 bg-white p-5 text-sm text-red-700">{error}</div> : null}{!loading && !error && messages.length === 0 ? <div className="rounded-[32px] bg-white p-10 text-center shadow-sm"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-[#FF385C]/10"><Sparkles className="h-7 w-7 text-[#FF385C]" /></div><h2 className="text-lg font-semibold text-neutral-950">Start the conversation</h2><p className="mt-2 text-sm text-neutral-500">Send a quick note about check-in, arrival time, or anything you need for this stay.</p></div> : null}{messages.map((msg, idx) => { const own = msg.senderId === currentUserId; return <React.Fragment key={msg.id}>{showDivider(messages, idx) ? <div className="my-6 flex items-center gap-4"><div className="h-px flex-1 bg-neutral-200"/><span className="text-xs font-semibold text-neutral-500">{formatDivider(msg.createdAt)}</span><div className="h-px flex-1 bg-neutral-200"/></div> : null}<div className={cn("mb-3 flex gap-3", own ? "justify-end" : "justify-start")}><div className={cn("flex max-w-[78%] flex-col", own ? "items-end" : "items-start")}>{!own ? <span className="mb-1 text-xs font-semibold text-neutral-500">{name}</span> : null}<div className={cn("rounded-[22px] px-4 py-3 text-[15px] leading-6 shadow-sm", own ? "rounded-br-md bg-neutral-950 text-white" : "rounded-bl-md bg-white text-neutral-900")}>{msg.body ? <p className="whitespace-pre-wrap break-words">{msg.body}</p> : null}{msg.attachments?.map((a, i) => a.type === "image" ? <img key={i} src={a.url} alt={a.name || "attachment"} className="mt-2 max-h-72 rounded-2xl object-cover" /> : null)}</div><span className="mt-1 text-[11px] text-neutral-400">{formatTime(msg.createdAt)}</span></div></div></React.Fragment>; })}</div></div>
    <div className="sticky bottom-0 shrink-0 border-t border-neutral-200 bg-white px-4 pb-[calc(env(safe-area-inset-bottom)+14px)] pt-3 md:px-8"><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-2 overflow-x-auto pb-1">{templates.map((tpl) => <button key={tpl} type="button" onClick={() => setText(tpl)} className="shrink-0 rounded-full border border-neutral-200 px-3 py-1.5 text-xs font-semibold text-neutral-700 hover:bg-neutral-50">{tpl}</button>)}</div>{attachments.map((a, i) => <div key={i} className="mb-2 flex items-center justify-between rounded-2xl bg-neutral-50 p-2 text-xs text-neutral-600"><span className="truncate">📷 {a.name || "Image attached"}</span><button onClick={() => setAttachments([])} className="font-bold text-neutral-900">Remove</button></div>)}<div className="flex items-end gap-2 rounded-[28px] border border-neutral-200 bg-white p-2 shadow-sm"><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(e) => onFiles(e.target.files)} /><button type="button" onClick={() => fileRef.current?.click()} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full hover:bg-neutral-100" aria-label="Attach image"><ImagePlus className="h-5 w-5 text-neutral-600" /></button><textarea ref={textareaRef} rows={1} value={text} onChange={(e) => setText(e.target.value)} onKeyDown={onKeyDown} placeholder={t("messages.typeMessage", "Type a message...")} className="max-h-32 flex-1 resize-none bg-transparent px-1 py-2.5 text-[15px] outline-none placeholder:text-neutral-400" /><button type="button" onClick={handleSend} disabled={(!text.trim() && attachments.length === 0) || sending} className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-full", text.trim() || attachments.length ? "bg-[#FF385C] text-white" : "bg-neutral-100 text-neutral-400")} aria-label="Send">{sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</button></div></div></div>
  </div>;
}
