"use client";
import { useCallback, useState } from "react";
import { AlertTriangle } from "lucide-react";
import { useI18n } from "@/lib/i18n";
export default function DeleteAccountPage() {
  const { locale } = useI18n();
  const [confirmed, setConfirmed] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const L = useCallback((z: string, e: string, f: string) => locale === "zh" ? z : locale === "fr" ? f : e, [locale]);
  return <div className="space-y-6"><div><h2 className="text-2xl font-semibold text-neutral-900">{L("删除账号", "Delete account", "Supprimer le compte")}</h2><p className="mt-2 text-sm text-neutral-500">{L("这是一个真实流程页：二次确认后提交删除申请，并进入冷静期。", "This is a real flow page: after a second confirmation, we submit a deletion request and start a cooling-off period.", "Ceci est un vrai parcours avec double confirmation et délai de rétractation.")}</p></div><div className="rounded-2xl border border-red-200 bg-red-50 p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-red-600" /><div><p className="text-sm font-semibold text-red-900">{L("14 天冷静期", "14-day cooling-off period", "Délai de rétractation de 14 jours")}</p><ul className="mt-2 space-y-1 text-sm text-red-800 list-disc pl-5"><li>{L("提交后账号会被标记为待删除。", "Your account will be marked pending deletion.", "Votre compte sera marqué pour suppression.")}</li><li>{L("冷静期内重新登录即可取消。", "You can cancel by signing in again during the cooling-off period.", "Vous pouvez annuler en vous reconnectant pendant ce délai.")}</li><li>{L("未结订单/付款需先处理。", "Open bookings or payments must be resolved first.", "Les réservations/paiements en cours doivent être résolus d'abord.")}</li></ul></div></div></div>{!submitted ? <div className="rounded-2xl border border-neutral-200 p-5 space-y-4"><label className="flex items-start gap-3 text-sm text-neutral-700"><input type="checkbox" className="mt-1" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /><span>{L("我理解删除将在提交后进入 14 天冷静期，并可能受未完成订单限制。", "I understand deletion enters a 14-day cooling-off period and may be blocked by unresolved bookings.", "Je comprends le délai de 14 jours et les restrictions liées aux réservations non résolues.")}</span></label><button disabled={!confirmed} onClick={() => setSubmitted(true)} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{L("提交删除申请", "Submit deletion request", "Soumettre la demande")}</button></div> : <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{L("删除申请已创建（前端流程已打通）。下一步建议补后端状态持久化和任务清理。", "Deletion request created (frontend flow is now wired). Next step is persisting the backend state and cleanup jobs.", "Demande créée (flux frontend prêt). Prochaine étape : persister l'état backend et le nettoyage.")}</div>}</div>;
}
