import { NextRequest, NextResponse } from "next/server";
import { getCurrentUserFromRequest } from "@/lib/auth";
import { getDb, userDb } from "@/lib/d1";
import { stripe } from "@/lib/stripe";
import { validateCsrf } from "@/lib/security/csrf";
export const dynamic = "force-dynamic";
async function ensureCustomer(userId: string, email?: string | null, name?: string | null) { const db = getDb(); const user = await userDb.findById(db, userId); const existing = (user as typeof user & { stripeCustomerId?: string | null })?.stripeCustomerId; if (existing) return existing; if (typeof stripe.customers?.create !== 'function') return null; const customer = await stripe.customers.create({ email: email || undefined, name: name || undefined, metadata: { userId } }); await db.prepare("UPDATE User SET stripeCustomerId = ?, updatedAt = ? WHERE id = ?").bind(customer.id, new Date().toISOString(), userId).run(); return customer.id; }
export async function GET(request: NextRequest) { try { const auth = await getCurrentUserFromRequest(request); if (!auth?.userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = getDb(); const user = await userDb.findById(db, auth.userId); const stripeCustomerId = (user as typeof user & { stripeCustomerId?: string | null })?.stripeCustomerId; if (!stripeCustomerId || typeof stripe.paymentMethods?.list !== 'function') return NextResponse.json({ paymentMethods: [], stripeReady: Boolean(process.env.STRIPE_SECRET_KEY) }); const methods = await stripe.paymentMethods.list({ customer: stripeCustomerId, type: 'card' }); const customer = typeof stripe.customers?.retrieve === 'function' ? await stripe.customers.retrieve(stripeCustomerId) : null; const defaultPaymentMethod = customer && !('deleted' in customer) ? customer.invoice_settings?.default_payment_method : null; return NextResponse.json({ paymentMethods: methods.data.map((pm) => ({ id: pm.id, brand: pm.card?.brand ?? 'card', last4: pm.card?.last4 ?? '----', expMonth: pm.card?.exp_month ?? null, expYear: pm.card?.exp_year ?? null, isDefault: defaultPaymentMethod === pm.id })), stripeReady: true }); } catch (error) { console.error('account/payments:get', error); return NextResponse.json({ error: 'Internal server error' }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { if (!validateCsrf(request)) return NextResponse.json({ error: "Invalid CSRF token" }, { status: 403 }); const auth = await getCurrentUserFromRequest(request); if (!auth?.userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = getDb(); const user = await userDb.findById(db, auth.userId); const customerId = await ensureCustomer(auth.userId, user?.email, user?.name); if (!customerId) return NextResponse.json({ error: 'Stripe not configured' }, { status: 503 }); const body = (await request.json()) as { paymentMethodId?: string }; if (!body.paymentMethodId) return NextResponse.json({ error: 'paymentMethodId is required' }, { status: 400 }); const paymentMethod = await stripe.paymentMethods.attach(body.paymentMethodId, { customer: customerId }); const customer = await stripe.customers.retrieve(customerId); const shouldDefault = !('deleted' in customer) && !customer.invoice_settings?.default_payment_method; if (shouldDefault) await stripe.customers.update(customerId, { invoice_settings: { default_payment_method: paymentMethod.id } }); return NextResponse.json({ ok: true, paymentMethod: { id: paymentMethod.id, brand: paymentMethod.card?.brand ?? 'card', last4: paymentMethod.card?.last4 ?? '----', expMonth: paymentMethod.card?.exp_month ?? null, expYear: paymentMethod.card?.exp_year ?? null, isDefault: shouldDefault } }); } catch (error) { console.error('account/payments:post', error); return NextResponse.json({ error: 'Internal server error' }, { status: 500 }); } }
